### ISSUE TITLE
Spark version not mentioned

### ISSUE THREAD

**Issue by tobiajo** [payberah/id2221#3]
The configs containing:

`py4j-0.8.2.1-src.zip`

Is _not_ applicable for Spark versions greater than 1.5.2.

**Comment by payberah** [comment]
I used spark 1.6.1 in the assignments, and I'm not sure if the codes are compatible with version less than it.

**Comment by tobiajo** [comment]
My misstake, I meant that `py4j-0.8.2.1-src.zip` works for Spark 1.5.x, with version 1.6.x it should be `py4j-0.9-src.zip`. Edited the issue.

**Comment by payberah** [comment]
It should work with spark 1.6.x as well. At least I didn't have any problem with this version.

**Comment by tobiajo** [comment]
The path is broken in 1.6.x., so I assume it is never used, since we're using Scala instead of Python.
